# Copyright (C) 2025 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This library is free software: you can redistribute it and/or
# modify it under the terms of the GNU Public License as published
# by the Free Software Foundation; either version 3 of the License,
# or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Public License along
# with this library.  If not, see
# <https://www.gnu.org/licenses/>.

default_language_version:
  python: python3 # Defaults to python2, so override it.

ci:
  skip:
    - lintr
    - style-files
    - readme-rmd-rendered
    - parsable-R
    - no-browser-statement
    - no-print-statement
    - no-debug-statement
    - deps-in-desc
    - use-tidy-description

exclude: ^tests/data
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9015
    hooks:
      - id: lintr
        args: [--warn_only]
      - id: style-files
        args: [--cache-root=styler]
      - id: readme-rmd-rendered
      - id: parsable-R
      - id: no-browser-statement
      - id: no-print-statement
      - id: no-debug-statement
      - id: deps-in-desc
      - id: use-tidy-description
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: (?x)(^src/RcppEigen)
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
  # Formatters should be run late so that they can re-format any prior changes.
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length", "120", "--target-version", "py313"]
  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--py", "313"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
      - id: clang-format
        types_or: [c, c++]
        exclude: (?x)(^src/RcppEigen)
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.22.3
    hooks:
      - id: gersemi
        exclude: (?x)(^cmake/modules)
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier
        language: node
        additional_dependencies: [prettier@3.6.2]
        types_or: [json, markdown, yaml]
        args: ["--write", "--ignore-unknown"]
