#!/usr/bin/env bash

# Copyright (C) 2025 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This library is free software: you can redistribute it and/or
# modify it under the terms of the GNU Public License as published
# by the Free Software Foundation; either version 3 of the License,
# or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Public License along
# with this library.  If not, see
# <https://www.gnu.org/licenses/>.

set -e
set -u
set -o pipefail

export CC=clang
export CXX=clang++

# shellcheck disable=SC2064
trap "cd '$PWD'" EXIT

git_root="$(git rev-parse --show-toplevel)"

conanfile="$git_root/deps/conanfile.py"
stage_dir="$git_root/staging/"

tmpdir="$(mktemp -d)"

# shellcheck disable=SC2064
trap "rm -rf '$tmpdir'" EXIT

version="$(
  grep 'version = "[[:digit:].]\+"' "$conanfile" |
  rev |
  cut -f 1 -d ' ' |
  rev |
  tr -d '"'
)"

cd "$tmpdir"  # deal with all the temp files generated by conan

for build_type in Release Debug; do
  conan create \
    "$conanfile" \
    -pr:a "$(basename "$CC")" \
    --settings="build_type=$build_type" \
    --build=missing \
    --build='hictk/*' \
    --update

  conan install \
    --requires="hictk/$version" \
    -pr:a "$(basename "$CC")" \
    --build=never \
    -s build_type=Release \
    --output-folder "$stage_dir/$build_type" \
    -g CMakeDeps
done
