# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

version <- function() {
    .Call(`_hictkR_version`)
}

nbins <- function(path, resolution) {
    .Call(`_hictkR_nbins`, path, resolution)
}

