# Copyright (C) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Deploy pkgdown website

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - ".github/workflows/pkgdown.yml"
      - "R/**"
      - "src/**"
      - "tests/**"
      - "conanfile.txt"
      - "hictk.conanfile.py"
      - "run_conan.py"
      - "DESCRIPTION"
      - "NAMESPACE"
    tags:
      - "v*.*.*"

  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/pkgdown.yml"
      - "R/**"
      - "src/**"
      - "tests/**"
      - "conanfile.txt"
      - "hictk.conanfile.py"
      - "run_conan.py"
      - "DESCRIPTION"
      - "NAMESPACE"
  release:
    types: [published]

env:
  HICTKR_CONAN_HOME: "${{ github.workspace }}/conan/"

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect number of CPUs
        run: |
          echo "NPROC=$(nproc)" >> "$GITHUB_ENV"
          echo "MAKE='make -j$(nproc)'" >> "$GITHUB_ENV"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
          Ncpus: ${{ env.NPROC }}

      - name: Restore Conan cache
        uses: actions/cache@v4
        id: restore-conan-cache
        with:
          key: conan-cache-pkgdown-${{ hashFiles('hictk.conanfile.py', 'conanfile.txt', 'run_conan.py') }}
          path: ${{ env.HICTKR_CONAN_HOME }}/p

      - name: Add requirements
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Clean Conan cache (post-build)
        if: steps.restore-conan-cache.outputs.cache-hit != 'true'
        run: |
          pip install 'conan>=2'

          export CONAN_HOME="$HICTKR_CONAN_HOME"

          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          clean: false
          branch: gh-pages
          folder: docs
