# Copyright (C) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: R CMD build

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - ".github/workflows/r-build.yml"
      - "R/**"
      - "src/**"
      - "tests/**"
      - "conanfile.txt"
      - "hictk.conanfile.py"
      - "run_conan.py"
      - "DESCRIPTION"
      - "NAMESPACE"
    tags:
      - "v*.*.*"

  pull_request:
    paths:
      - ".github/workflows/r-build.yml"
      - "R/**"
      - "src/**"
      - "tests/**"
      - "conanfile.txt"
      - "hictk.conanfile.py"
      - "run_conan.py"
      - "DESCRIPTION"
      - "NAMESPACE"

  release:
    types:
      - published

env:
  HICTKR_CONAN_HOME: "${{ github.workspace }}/.conan2/"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  r-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Detect number of CPUs
        run: |
          echo "NPROC=$(nproc)" >> "$GITHUB_ENV"
          echo "MAKE='make -j$(nproc)'" >> "$GITHUB_ENV"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
          Ncpus: ${{ env.NPROC }}

      - name: Add requirements
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Setup Latex
        uses: r-lib/actions/setup-tinytex@v2

      - name: Restore Conan cache
        uses: actions/cache@v4
        id: restore-conan-cache
        with:
          key: conan-cache-r-build-${{ hashFiles('hictk.conanfile.py', 'conanfile.txt', 'run_conan.py') }}
          path: ${{ env.HICTKR_CONAN_HOME }}/p

      - name: Build package
        run: R CMD build .

      - name: Check package
        run: R CMD check hictkR_*.*.*.tar.gz --as-cran

      - name: Clean Conan cache (post-build)
        if: steps.restore-conan-cache.outputs.cache-hit != 'true'
        run: |
          pip install 'conan>=2'

          export CONAN_HOME="$HICTKR_CONAN_HOME"

          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: hictkR_*.*.*.tar.gz
          if-no-files-found: "error"
          retention-days: 7
          compression-level: 0

  ci-status-check:
    name: Status Check (R CMD build)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - r-build

    steps:
      - name: Collect job results
        if: needs.r-build.result != 'success'
        run: exit 1
