# Copyright (C) 2025 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This library is free software: you can redistribute it and/or
# modify it under the terms of the GNU Public License as published
# by the Free Software Foundation; either version 3 of the License,
# or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Public License along
# with this library.  If not, see
# <https://www.gnu.org/licenses/>.

name: R CMD build

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - ".github/workflows/r-build.yml"
      - "deps/conanfile.py"
      - "deps/generate_makevars.py"
      - "R/**"
      - "inst/extdata/**"
      - "man/**"
      - "src/**"
      - "tests/**"
      - ".Rbuildignore"
      - "configure"
      - "configure.win"
      - "DESCRIPTION"
      - "NAMESPACE"
    tags:
      - "v*.*.*"

  pull_request:
    paths:
      - ".github/workflows/r-build.yml"
      - "deps/conanfile.py"
      - "deps/generate_makevars.py"
      - "R/**"
      - "inst/extdata/**"
      - "man/**"
      - "src/**"
      - "tests/**"
      - ".Rbuildignore"
      - "configure"
      - "configure.win"
      - "DESCRIPTION"
      - "NAMESPACE"

  release:
    types:
      - published

env:
  HICTKR_CONAN_HOME: "${{ github.workspace }}/.conan2/"
  CC: "gcc"
  CXX: "g++"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  r-build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Detect number of CPUs
        run: |
          echo "NPROC=$(nproc)" >> "$GITHUB_ENV"
          echo "MAKE='make -j$(nproc)'" >> "$GITHUB_ENV"

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
          Ncpus: ${{ env.NPROC }}

      - name: Add requirements
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::devtools
          needs: check

      - name: Setup Latex
        uses: r-lib/actions/setup-tinytex@v2

      - name: Restore Conan cache
        uses: actions/cache@v4
        id: restore-conan-cache
        with:
          key: conan-cache-r-build-${{ hashFiles( 'configure', 'deps/conanfile.py', 'deps/generate_makevars.py') }}
          path: ${{ env.HICTKR_CONAN_HOME }}/p

      - name: Build package
        run: R CMD build .

      - name: Check package
        run: R CMD check hictkR_*.*.*.tar.gz --as-cran

      - name: Setup Python
        if: steps.restore-conan-cache.outputs.cache-hit != 'true'
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Clean Conan cache (post-build)
        if: steps.restore-conan-cache.outputs.cache-hit != 'true'
        run: |
          pip install 'conan>=2'

          export CONAN_HOME="$HICTKR_CONAN_HOME"

          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source

      - name: Ensure the documentation is up-to-date
        run: |
          Rscript -e 'devtools::document()'
          git diff --exit-code man/

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: hictkR_*.*.*.tar.gz
          if-no-files-found: "error"
          retention-days: 7
          compression-level: 0

  ci-status-check:
    name: Status Check (R CMD build)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - r-build

    steps:
      - name: Collect job results
        if: needs.r-build.result != 'success'
        run: exit 1
